"""add financial_vitals table and vitals_prompt_dismissed_at

Revision ID: 611273bf187f
Revises: f7c1a2e9b4d6
Create Date: 2026-09-01 21:03:23.492706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '611273bf187f'
down_revision: Union[str, Sequence[str], None] = 'f7c1a2e9b4d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_vitals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('take_home_pay_monthly_cents', sa.Integer(), nullable=False),
    sa.Column('rent_or_mortgage_monthly_cents', sa.Integer(), nullable=False),
    sa.Column('car_payment_monthly_cents', sa.Integer(), nullable=False),
    sa.Column('monthly_spend_estimate_cents', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('financial_vitals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financial_vitals_user_id'), ['user_id'], unique=True)

    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vitals_prompt_dismissed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.drop_column('vitals_prompt_dismissed_at')

    with op.batch_alter_table('financial_vitals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financial_vitals_user_id'))

    op.drop_table('financial_vitals')
    # ### end Alembic commands ###
