"""Add chat_usage table for daily chat rate limiting

Revision ID: a9bf51a171f8
Revises: b03fd93850c2
Create Date: 2026-08-13 22:29:32.832635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a9bf51a171f8'
down_revision: Union[str, Sequence[str], None] = 'b03fd93850c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('usage_date', sa.Date(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'usage_date')
    )
    with op.batch_alter_table('chat_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_usage_usage_date'), ['usage_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_usage_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_usage_user_id'))
        batch_op.drop_index(batch_op.f('ix_chat_usage_usage_date'))

    op.drop_table('chat_usage')
    # ### end Alembic commands ###
