"""initial schema

Revision ID: b03fd93850c2
Revises: 
Create Date: 2026-07-29 22:13:35.732028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b03fd93850c2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_user_email'), ['email'], unique=True)

    op.create_table('merchantcategorycache',
    sa.Column('merchant_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('primary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subcategory', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('merchant_key')
    )
    op.create_table('importjob',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('processing', 'pending_income_review', 'completed', name='importstatus'), nullable=False),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('total_transactions', sa.Integer(), nullable=False),
    sa.Column('file_results_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('importjob', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_importjob_user_id'), ['user_id'], unique=False)

    op.create_table('insight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('import_job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('insight_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('explanation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('confidence_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('time_period_start', sa.Date(), nullable=True),
    sa.Column('time_period_end', sa.Date(), nullable=True),
    sa.Column('supporting_transaction_ids', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('suggested_next_step', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_dismissed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('meta_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('insight', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_insight_import_job_id'), ['import_job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_insight_user_id'), ['user_id'], unique=False)

    op.create_table('merchantrule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('merchant_pattern', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('primary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subcategory', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('match_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('merchantrule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_merchantrule_merchant_pattern'), ['merchant_pattern'], unique=False)
        batch_op.create_index(batch_op.f('ix_merchantrule_user_id'), ['user_id'], unique=False)

    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('import_job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.LargeBinary(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('transaction_type', sa.Enum('debit', 'credit', name='transactiontype'), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_last4', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('institution', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_file_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_income_candidate', sa.Boolean(), nullable=False),
    sa.Column('income_category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('income_confirmed', sa.Boolean(), nullable=True),
    sa.Column('expense_category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('expense_subcategory', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category_source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category_confidence', sa.Float(), nullable=True),
    sa.Column('confidence_label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_ambiguous', sa.Boolean(), nullable=False),
    sa.Column('ambiguity_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('is_transfer', sa.Boolean(), nullable=False),
    sa.Column('transfer_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('transfer_pair_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_import_job_id'), ['import_job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_source_file_hash'), ['source_file_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_user_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_source_file_hash'))
        batch_op.drop_index(batch_op.f('ix_transaction_import_job_id'))

    op.drop_table('transaction')
    with op.batch_alter_table('merchantrule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_merchantrule_user_id'))
        batch_op.drop_index(batch_op.f('ix_merchantrule_merchant_pattern'))

    op.drop_table('merchantrule')
    with op.batch_alter_table('insight', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_insight_user_id'))
        batch_op.drop_index(batch_op.f('ix_insight_import_job_id'))

    op.drop_table('insight')
    with op.batch_alter_table('importjob', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_importjob_user_id'))

    op.drop_table('importjob')
    op.drop_table('merchantcategorycache')
    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_user_email'))

    op.drop_table('app_user')
    # ### end Alembic commands ###
