"""Add password reset token table

Revision ID: b59ee9b38be3
Revises: e32b13469336
Create Date: 2026-08-16 16:40:48.809053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b59ee9b38be3'
down_revision: Union[str, Sequence[str], None] = 'e32b13469336'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passwordresettoken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('passwordresettoken', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_passwordresettoken_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_passwordresettoken_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('passwordresettoken', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_passwordresettoken_user_id'))
        batch_op.drop_index(batch_op.f('ix_passwordresettoken_token_hash'))

    op.drop_table('passwordresettoken')
    # ### end Alembic commands ###
